/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnotherPages: typeof import('./src/components/AnotherPages.vue')['default']
    AppNavDrawer: typeof import('./src/components/App/NavDrawer.vue')['default']
    AppNavText: typeof import('./src/components/App/NavText.vue')['default']
    AppSidebarMenus: typeof import('./src/components/App/SidebarMenus.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
